FROM public.ecr.aws/lambda/provided:al2

RUN yum install -y php-cli && yum clean all && command -v php
COPY lambda/bootstrap.txt /var/runtime/bootstrap
COPY lambda/handler.php /var/task/handler.php
RUN chmod +x /var/runtime/bootstrap
CMD ["bootstrap"]
