#!/usr/bin/env python3

import sys
import random
import pathlib
import threading
import concurrent.futures

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
sys.dont_write_bytecode = True
import llmj

FAKE_TEXT_CNT = 30

PROMPT_TEMPLATE = 'Generate a __ARTICLE__ of approximately __LENGTH__ characters written in __LANG__ about __GENRE__. The content does not need to describe real events. Use a __FORMALITY__ tone and a __STYLE__ writing style.'

def fake_text():
    spec = {
        'lang' : 'Japanese',
        'length' : random.randint(300, 3000),
        'article' : random.choice([
            'fact-based article ( must be based on real facts )',
            'fictional article ( write it as if it were a real news article; the events do not need to be real )'
        ]),
        'formality' : random.choice([
            'Formal',
            'Neutral',
            'Conversational'
        ]),
        'style' : random.choice([
            'Objective',
            'Analytical',
            'Explanatory',
            'Narrative'
        ]),
        'genre' : random.choice([
            'Manga & Digital Comics',
            'Character Design',
            '2D & 3D Animation',
            'Animated Movies',
            'Animation Reviews',
            'Animated Series',
            'Art Exhibitions',
            'Sculpture',
            'Photography',
            'Painting',
            'Fashion Design',
            'Graphic Design',
            'Illustration',
            'Contemporary Art',
            'Art Techniques',
            'Art Classes & Workshops',
            'Art Education & Tutorials',
            'Slice of Life & Sitcom',
            'Viral Comedy',
            'Satire',
            'Humor',
            'Parody',
            'Verbal Arts & Storytelling',
            'Sketches, Manzai, Duo Comedy & Improv',
            'Comedians',
            'Woodworking',
            'Handicrafts',
            'Paper Crafts',
            'Upcycled Crafts',
            'Celebrity News & Topics',
            'Mystery',
            'Paranormal & Urban Legends',
            'Traditional Culture &  Multiculturalism',
            'Contemporary Culture & Social Culture',
            'Variety & Infotainment Shows',
            'Documentary Shows',
            'Drama & Fictional Shows',
            'Kids & Educational Shows',
            'News Shows',
            'Quizzes, Fortune-Telling & Trivia',
            'Performing Arts',
            'Live Performances & Events',
            'Role-Playing Games',
            'Adventure Games',
            'Action Games',
            'Shooting Games',
            'Strategy Games',
            'Simulation Games',
            'Brain Training & Educational Games',
            'Music & Rhythm Games',
            'Quiz & Puzzle Games',
            'Horror Games',
            'Board & Card Games',
            'Family & Casual Games',
            'Sports Games',
            'Console Games',
            'Mobile Games',
            'VR & AR Games',
            'eSports',
            'Gameplay Videos & Streams',
            'Action Movies',
            'Sci-Fi Movies',
            'Suspense & Mystery Movies',
            'Horror, Thriller & Disaster Movies',
            'Romance Movies',
            'Fantasy Movies',
            'Drama Movies',
            'Comedy Movies',
            'Documentary Movies',
            'History & War Movies',
            'Sports Movies',
            'Adventure Movies',
            'Westerns',
            'Music & Musical Movies',
            'Crime Movies',
            'Gangster & Outlaw Movies',
            'Period Movies',
            'Movie Reviews',
            'Movie Trailers & Teasers',
            'Movie Analysis & Criticism',
            'Making-of & Interviews',
            'J-Pop',
            'K-Pop',
            'Western Music',
            'Music Theory',
            'Music History & Cultural Studies',
            'Instrument Performance & Analysis',
            'Lyric Analysis & Composition Studies',
            'Music Reviews',
            'Parent-Child Relationships',
            'Parenting Support',
            'Child Development',
            'Child Psychology',
            'Educational Play & Activities',
            'Family Life',
            'Parenting Tips',
            'Yoga & Meditation',
            'Gym & Strength Training',
            'Light Workouts',
            'Cardio & Endurance Training',
            'Fitness Equipment Reviews',
            'Weight Loss & Body Shaping',
            'Internal Medicine, Surgery & General Medicine',
            'OB-GYN (Obstetrics and Gynecology) & Pediatrics',
            'Mental Health & Psychiatry',
            'Orthopedics & Plastic Surgery',
            'Dermatology',
            'Cosmetic Medicine & Cosmetic Surgery',
            'Ophthalmology, ENT (Otolaryngology) & Dentistry',
            'Specialized Medical Fields',
            'Hospitals & Clinics',
            'Health Checkups & Comprehensive Health Screening',
            'Medical Technology, Research & Rehabilitation',
            'Medications & Prescriptions',
            'Preventive Medicine & Disease Management',
            'Anma (Massage), Seitai (Chiropractic) & Acupuncture',
            'Kanpo (Herbal Medicine) & East Asian Medicine',
            'Health & Medical Services',
            'Nutrition & Supplements',
            'Well-being',
            'Children\'s Health',
            'Men\'s Health',
            'Women\'s Health',
            'Senior Health',
            'Romance',
            'Long-Distance & International Romance',
            'Breakups & Reconciliation',
            'Infidelity & Complex Relationships',
            'Wedding Preparation & Matchmaking',
            'Marriage & Partnerships',
            'Interpersonal Relationships',
            'Goal Setting & Goal Planning',
            'Creativity & Ideation',
            'Productivity & Time Management',
            'Personality Development & Self-Awareness',
            'Motivation & Habit Building',
            'Emotional Management',
            'Leadership & Interpersonal Skills',
            'Mindset & Mental Models',
            'Stress Management & Coping',
            'Improving Communication Skills',
            'Vehicle Reviews & Test Drives',
            'Maintenance, Inspections & Customization',
            'Car Sales & Used Car Deals',
            'Parts & Accessories for Car & Bikes',
            'Electric Vehicles & High-Performance Vehicles',
            'History of Vehicles & Technology of Vehicles',
            'Driving Skills & Techniques',
            'Car Rentals & Chauffeur Services',
            'Roadside Assistance & Towing',
            'Gas Stations & Charging Spots',
            'Trains, Buses & Cable Cars',
            'Airlines & Airports',
            'Sightseeing & Charter Bus Services',
            'Parking & Traffic Information Services',
            'Driver\'s License',
            'Entrepreneurship Know-How',
            'Entrepreneurship & Management Mindset',
            'Marketing & Branding Strategy',
            'Human Resources & Organizational Management',
            'Customer Service & Customer Strategy',
            'Work Environment & Work Style',
            'Industry Trends & Topics',
            'Business Events',
            'Economic Data Analysis & Statistics',
            'Financial Systems & Monetary Policy',
            'Economic Policy & Fiscal Management',
            'Global Economy & International Trade',
            'Morning Lifestyle',
            'Night Lifestyle',
            'Household Chores',
            'Solo Time & Home Moments',
            'Daily Life with Family',
            'Weekend & Holiday Lifestyle',
            'Investment Strategy & Asset Management',
            'Stocks & Fund Investment',
            'Real Estate Investment & Mortgages',
            'Credit Scores & Loan Management',
            'Taxes & Tax Saving Strategies',
            'Post-Retirement Funding Plans',
            'Money Saving Tips & Money Management',
            'Coupons, Points & Rewards Activities',
            'Deals & Sales Alerts',
            'Household Budget Management',
            'Use of Cashless Payments',
            'Use of Second-Hand Goods & Resale Markets',
            'Tax Saving & Deduction Systems',
            'Relaxation, ASMR & Satisfying Media',
            'Social Networking Services',
            'Message Boards & Forums',
            'Personal Blogs, Diaries, Photos, & Videos',
            'File Sharing & Resource Distribution Services',
            'Virtual Space & Avatar Culture',
            'Dating & Social Matching Apps',
            'Home Appliances, Computers & Audio Visual Equipment',
            'Furniture & Interior Goods',
            'Kitchenware & Household Goods',
            'Children\'s Clothing & Baby Products',
            'Cosmetics, Beauty & Personal Care Products',
            'Optical, Hearing Aids & Health-Related Goods',
            'Books, Stationery & Physical Media',
            'Watches, Accessories & Precious Metals',
            'Fashion & Apparel',
            'Toys & Hobbies',
            'Department Stores & Shopping Malls',
            'Supermarkets & Discount Stores',
            'Convenience Stores',
            'Home & Garden Stores',
            'Second-hand & Thrift Stores',
            'Ticketing Services & Ticket Offices',
            'Buddhist & Religious Supplies',
            'Home Hardware & DIY Supplies',
            'Office & Business Supplies',
            'Flowers, Plants & Gardening Supplies',
            'Medicines & Drugstores',
            'Mobile, Smartphone Devices & Accessories',
            'Musical Instruments',
            'Gifts & Greeting Cards',
            'Party Supplies & Decorations',
            'Sales & Promotions',
            'General Shopping',
            'Smartphones & Tablets',
            'Desktop & Laptop Computers',
            'Home Electronics & Smart Devices',
            'Cameras & Audio Visual Equipment',
            'Wearable Devices',
            'Computer Peripherals & Accessories',
            'Electronics Reviews & Comparisons',
            'Programming & Development Tutorials',
            'Software Development & Design',
            'Game Development',
            'Web & Application Development',
            'Cloud & Server Technology',
            'Data Science & Machine Learning',
            'Artificial Intelligence & Deep Learning',
            'Cybersecurity',
            'Computer Science in General',
            'Extended Reality (VR, AR, MR)',
            'Drone & Robotics Technology',
            'Cryptocurrency & Blockchain',
            'Electronic Work',
            'Microcontroller Utilization',
            'Career Design & Goal Setting',
            'Skills Development & Certification Acquisition',
            'Career Change & Job Transition',
            'Side Jobs & Freelancing',
            'New Graduates & Job Hunting',
            'Business Etiquette & Basic Professional Skills',
            'Work Styles & Remote Work System',
            'Life with Pets',
            'Animal Training & Understanding Behavior',
            'Animal Health & Veterinary Care',
            'Animal Rescue & Fosterage',
            'Familiar Creatures',
            'Wildlife',
            'Reading Habits & Book Recommendations',
            'Book Reviews & Recommendations',
            'Literary Interpretation & Analysis',
            'Contemporary Fiction & Light Novels',
            'Classic Literature',
            'Poetry, Short Stories & Essays',
            'Non-Fiction & Practical Guides',
            'Children\'s & Young Adult Books',
            'Photography & Art Books',
            'Author Interviews',
            'Publishing & Bookshop Culture',
            'E-Books & Digital Reading',
            'Audiobooks',
            'Women\'s Fashion',
            'Men\'s Fashion',
            'Kimono & Traditional Japanese Wear',
            'Shoes, Bags & Fashion Goods',
            'Accessories & Jewelry',
            'Makeup',
            'Nails & Nail Art',
            'Hair Styling',
            'Skincare & Facial Care',
            'Fashion & Beauty Reviews',
            'Trend Analysis & Outfit Suggestions',
            'Fashion Culture',
            'Gourmet Reviews & Blogs',
            'Dining Occasions',
            'Restaurants & Eateries Introductions',
            'Alcoholic Beverages',
            'Bento & Food Delivery',
            'Sweets, Desserts & Confectionery',
            'Japanese Cuisine & Regional Dishes',
            'Chinese Cuisine',
            'Korean Cuisine',
            'Asian & Ethnic Cuisines',
            'Western Cuisine',
            'International & Fusion Cuisine',
            'Healthy & Dietetic Cooking',
            'Food Culture & Background',
            'Ingredients Selection & Usage',
            'Cooking Methods & Style Introduction',
            'Cooking Recipes',
            'Room Styling & Redecoration',
            'Organization & Storage Ideas',
            'Home & Garden Decoration',
            'Remote Work & Home Office Setup',
            'Renovation & Home Repair',
            'Gardening & Plant Care',
            'Interior Styles & Color Usage',
            'Home Improvement DIY',
            'Housing',
            'Everyday Values & Ways of Living',
            'Social Interactions & Sense of Manners',
            'Relationship with Social media and Information',
            'World Religions & Traditional Religions',
            'Belief & Spirituality',
            'Religion & Society',
            'Baseball',
            'Soccer & Football',
            'Basketball',
            'Volleyball',
            'Tennis',
            'Table Tennis',
            'Golf',
            'Rugby',
            'Martial Arts & Combat Sports',
            'Gymnastics, Dance & Fitness',
            'Swimming & Aquatic Sports',
            'Track & Field',
            'Skiing, Snowboarding & Winter Sports',
            'Water Sports & Marine Sports',
            'Motorsports',
            'Sports Schools & Classes',
            'Gyms & Training Facilities',
            'Stadiums, Arenas & Sports Venues',
            'Sports Gear & Equipment',
            'Sports News & Highlights',
            'Spectating & Fan Culture',
            'Mind Sports',
            'Tourist Attractions & Landmarks',
            'Nature & Landscapes',
            'Accommodations',
            'Travel Preparation & Travel Tips',
            'Travel Reviews & Travelogues',
            'Experience & Activities',
            'Theme Parks & Amusement Facilities',
            'Zoos & Aquariums',
            'Museums, Art Galleries & Science Centers',
            'Hot Springs, Spas & Public Baths',
            'Gambling & Government-Authorized Racing',
            'Diversity, Equity & Inclusion Issues',
            'Volunteering & Community Service',
            'Donations & Crowdfunding Activities',
            'Social Enterprises & Sustainable Business',
            'Community & Grassroots Movements',
            'History, Geography & Social Studies',
            'Literature, Philosophy & Cultural Heritage',
            'Economics, Politics & Law',
            'Science, Chemistry, Physics & Biology',
            'Math, Statistics & Data Science',
            'Environment, Earth & Astronomy',
            'Psychology, Neuroscience & Medicine',
            'Arts, Music & Creative Expression',
            'Technology & Computer Science',
            'Elementary Education & Secondary Education',
            'Higher Education & University Education',
            'Educational Policy & Educational System',
            'Pedagogy & Educational Technology',
            'Human Rights & Social Change',
            'Multicultural Understanding & Global Issues',
            'Health, Physical Education & Life Environment Studies',
            'English Learning',
            'Japanese Learning',
            'Korean Learning',
            'Chinese Learning',
            'French Learning',
            'Spanish Learning',
            'Multiple Languages & General Language Learning',
            'Understanding Grammar, Vocabulary & Syntax',
            'Pronunciation & Listening Improvement',
            'Language Exchange',
            'Law & Judicial Systems',
            'Social Order & Public Safety',
            'Military, Defense & Security',
            'Central Government, Ministries & Administrative Policies',
            'Local Governments & Regional Administration',
            'Public Policy & Welfare System',
            'Understanding Policies & Systems',
            'Political Thought, Ideology & Governance',
            'Political Parties, Elections & Political Trends',
            'Comparative Politics & Institutional Studies',
            'Foreign Policy & International Cooperation',
            'Media & Politics',
            'International News',
            'Political & Economy News',
            'Weather, Disasters & Public Safety',
            'Incidents & Social News',
            'Poverty, Inequality & Living Difficulties',
            'Human Rights, Diversity & Gender',
            'Environment, Climate Change',
            'Health, Medicine & Welfare',
            'Lifestyle Information & Practical Wisdom',
            'Public Safety & Disaster Prevention',
            'IT & Technology',
            'Academic & Research',
            'Archives & Documents',
            'Language, Dictionaries, Translation Tools & Translation Resources',
            'Geography & Global Data',
            'Science & Technology Documents',
            'Encyclopedias & General Reference'
        ])
    }
    prompt = llmj.text_from_template_text(PROMPT_TEMPLATE, {
        '__LANG__' : spec['lang'],
        '__LENGTH__' : spec['length'],
        '__ARTICLE__' : spec['article'],
        '__FORMALITY__' : spec['formality'],
        '__STYLE__' : spec['style'],
        '__GENRE__' : spec['genre']
    })
    # print(prompt)
    return llmj.RUNNER.toText(prompt)

completed = 0
lock = threading.Lock()

def generate(in_counter, in_digits):
    global completed
    path = llmj.DIR_SOURCE / (str(in_counter).zfill(in_digits) + '.txt')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(fake_text())
    with lock:
        completed += 1
        progress = completed * 100 / FAKE_TEXT_CNT
        print(f'INFO : {progress:.1f}% ({completed}/{FAKE_TEXT_CNT})')

def main():
    digits = 3
    maxCounter = -1
    for path in llmj.DIR_SOURCE.glob('*.txt'):
        try:
            maxCounter = max(maxCounter, int(path.stem))
        except ValueError:
            pass
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
        futures = []
        for i in range(FAKE_TEXT_CNT):
            futures.append(executor.submit(generate, maxCounter + 1 + i, digits))
        for future in concurrent.futures.as_completed(futures):
            future.result()
    llmj.finalize()

if __name__ == '__main__':
    main()
