name: Deploy to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pj-corridor.net/index.html'
      - 'pj-corridor.net/images/**'
      - 'pj-corridor.net/cube3d/**'
      - 'stick-figure/**'
      - 'pj-corridor.net/personalitytest/**'
      - 'pj-corridor.net/gallery-256/**'
      - 'pj-corridor.net/gallery-fullcolor/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      INDEXPATH: pj-corridor.net/index.html
      IMAGEPATH: pj-corridor.net/images/
      APPL1PATH: pj-corridor.net/cube3d/
      APPL2PATH: stick-figure/
      APPL3PATH: pj-corridor.net/personalitytest/
      GA256PATH: pj-corridor.net/gallery-256/
      GAFULPATH: pj-corridor.net/gallery-fullcolor/
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: configure credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: pre-check modified
      run: |
        git fetch --depth=2
        echo "CURR_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "PREV_SHA=$(git rev-parse ${{ github.sha }}^)" >> $GITHUB_ENV
        echo "CURR_SHA=${{ github.sha }}"
        echo "PREV_SHA=$(git rev-parse ${{ github.sha }}^)"
    - name: check modified
      run: |
        FILES=$(git diff --name-only $PREV_SHA $CURR_SHA | tr '\n' ' ')
        echo "FILES=$FILES" >> $GITHUB_ENV
    - name: copy-1
      if: contains(env.FILES, env.INDEXPATH)
      run: |
        aws s3 cp ${{ env.INDEXPATH }} s3://pj-corridor.net/index.html
    - name: sync-1
      if: contains(env.FILES, env.IMAGEPATH)
      run: |
        aws s3 sync ${{ env.IMAGEPATH }} s3://pj-corridor.net/images/ --exclude ".git/*"
    - name: sync-2
      if: contains(env.FILES, env.APPL1PATH)
      run: |
        echo "${{ github.sha }}" > version.txt
        aws s3 cp version.txt s3://pj-corridor.net/cube3d/version.txt
        aws s3 sync ${{ env.APPL1PATH }} s3://pj-corridor.net/cube3d/ --exclude ".git/*"
    - name: sync-3
      if: contains(env.FILES, env.APPL2PATH)
      run: |
        echo "${{ github.sha }}" > version.txt
        aws s3 cp version.txt s3://pj-corridor.net/stick-figure/version.txt
        aws s3 sync ${{ env.APPL2PATH }} s3://pj-corridor.net/stick-figure/ --exclude ".git/*"
    - name: sync-4
      if: contains(env.FILES, env.APPL3PATH)
      run: |
        aws s3 sync ${{ env.APPL3PATH }} s3://pj-corridor.net/personalitytest/ --exclude ".git/*"
    - name: sync-5
      if: contains(env.FILES, env.GA256PATH)
      run: |
        aws s3 sync ${{ env.GA256PATH }} s3://pj-corridor.net/gallery-256/ --exclude ".git/*"
    - name: sync-6
      if: contains(env.FILES, env.GAFULPATH)
      run: |
        aws s3 sync ${{ env.GAFULPATH }} s3://pj-corridor.net/gallery-fullcolor/ --exclude ".git/*"
    - name: clear cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"

